import type { Metadata } from "next"
import localFont from "next/font/local"
import "../globals.css"
import Providers from "~/components/providers"
import { Toaster } from "~/components/ui/toaster"
import NextTopLoader from "nextjs-toploader"
import { BreakpointOverlay } from "~/components/breakpoint-overlay"
import { appMode } from "~/app-config"
import Header from "../_header/header"

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [
    { rel: "icon", type: "image/png", sizes: "48x48", url: "/favicon.ico" },
  ],
  keywords:
    "next.js, starter kit, saas, ecommerce, digital products, saas code kit, indie hacking, indie hacker kit, micro saas, entrepreneurship, Code Starter Kit, SaaS Product Launch, Code Documentation Tutorial, Beginner Coding Kit, Start-up SaaS Kit, Coding Guides and Resources, Video Tutorials for Coding, Beginner SaaS Guide, Launch your First SaaS, Step-by-step Coding Kit, SaaS Launch Kit, Software as a Service Starter, Easy Code Launch Kit, Coding Skills for SaaS, Starter Kit for SaaS, Code, Document, Launch, Comprehensive Coding Starter Kit, Master SaaS Product Launch, SaaS Documentation Tutorial, First-Time Coders Kit, SaaS coding course, Initiate SaaS Journey, Seamless SaaS Launch Guide, First SaaS Product Guidance, Bootstrap SaaS Tutorial, Ultimate SaaS Starter Pack, Learning Guide for SaaS, DIY SaaS Kit, Code your SaaS Product, All-in-one Coding Starter Kit",
  openGraph:
    appMode === "comingSoon"
      ? {
          title: "nextjs-template-v2-2024.com",
          description:
            "The ultimate template v2 of nextjs in 2024 with a collection of technologies",
          url: "https://nextjs-template-v2-2024.com",
          siteName: "localhost",
          type: "website",
          images: [
            {
              url: "https://nextjs-template-v2-2024.com/nextjs-template-v2-2024.png",
              secureUrl:
                "https://nextjs-template-v2-2024.com/nextjs-template-v2-2024.png",
              width: 800,
              height: 418,
              alt: "The nextjs-template-v2-2024.com social media card image",
            },
          ],
        }
      : undefined,
}

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "vn" }]
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <NextTopLoader />
          {appMode === "live" && <Header />}
          {children}
        </Providers>
        <Toaster />
        <BreakpointOverlay />
      </body>
    </html>
  )
}
